# Generated by Django 5.1.1 on 2024-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="port",
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
    ]
