# Generated by Django 5.1.1 on 2024-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_card_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="login",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="password",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="ip",
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="card",
            name="port",
            field=models.PositiveIntegerField(default=80),
        ),
    ]
