# Generated by Django 5.1.1 on 2024-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_card_login_card_password_alter_card_ip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="card",
            name="up_date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
